name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: ['*', 16, 14, 12]
        hapi: [20, 19, 18, 17]

    runs-on: ubuntu-latest
    name: Test node@${{ matrix.node }} hapi@${{ matrix.hapi }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: ${{ matrix.node-version == '*' }}
    - run: npm install
    - run: npm install @hapi/hapi@${{ matrix.hapi }}
    - run: npm test